---
name: Coordinates
version: 1.0.1
main: NhanAZ\Coordinates\Main
api: 5.0.0
src-namespace-prefix: NhanAZ\Coordinates
author: NhanAZ
description: Show coordinates
website: https://github.com/NhanAZ
...
